# Generated by Django 4.2.17 on 2026-03-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Имя")),
                ("surname", models.CharField(max_length=250, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(max_length=250, verbose_name="Отчество"),
                ),
                (
                    "work_experience",
                    models.IntegerField(default=0, verbose_name="Стаж работы"),
                ),
                (
                    "specialization",
                    models.CharField(max_length=250, verbose_name="Специализация"),
                ),
                (
                    "science",
                    models.TextField(verbose_name="Ученая степень / Категория"),
                ),
                ("post", models.CharField(max_length=250, verbose_name="Должность")),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="doctors/photo",
                        verbose_name="Картинка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Врач",
                "verbose_name_plural": "Врачи",
            },
        ),
    ]
